/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonThemes: typeof import('./src/components/Button/ButtonThemes.vue')['default']
    ChatCard: typeof import('./src/components/Chat/chatCard.vue')['default']
    ChatSearch: typeof import('./src/components/Chat/chatSearch.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    MyAside: typeof import('./src/components/Chat/myAside.vue')['default']
    MyLaoding: typeof import('./src/components/myLaoding.vue')['default']
    NewChatButton: typeof import('./src/components/Button/newChatButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
